version: '3.7'
services:
  backend:
    environment:
      - SERVER_HOST=http://${DOMAIN}
  db:
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_DB=${POSTGRES_DB:-corgi-dev}
      - POSTGRES_USER=${POSTGRES_USER:-corgi-dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD:-trust}
  concourse:
    environment:
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: postgres
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: postgres
      CONCOURSE_EXTERNAL_URL: http://localhost:8100
      CONCOURSE_ADD_LOCAL_USER: dev:dev
      CONCOURSE_MAIN_TEAM_LOCAL_USER: dev
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
  