version: '3.7'
services:
  backend-tests:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        env: dev
    command: bash -c "while true; do sleep 1; done"
    env_file:
      - env-backend.env
    environment:
      - SERVER_NAME=backend
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=
      - PG_DBNAME=tests
  backend:
    environment:
      - SERVER_NAME=backend
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=
      - PG_DBNAME=tests
