version: '3.7'
services:
# Uncomment lines below to create Infinite loop to keep container live doing nothing
#   backend:
#     command: bash -c "while true; do sleep 1; done"
  backend:
    command: ./bin/prestart-dev.sh
  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=DEBUG \
      --accessLog \
      --web
  concourse:
    command: quickstart
