version: '3.7'
services:
  backend:
    env_file:
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      - REVISION=${REVISION}
      - TAG=${TAG}
      - STACK_NAME=${STACK_NAME}
      - DEPLOYED_AT=${DEPLOYED_AT}
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_DB=${POSTGRES_DB:-corgi-dev}
      - POSTGRES_USER=${POSTGRES_USER:-corgi-dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD:-trust}

