version: '3.7'
services:
  backend:
    environment:
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
      - SERVER_HOST=http://${DOMAIN}
  concourse:
    environment:
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: postgres
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: postgres
      CONCOURSE_EXTERNAL_URL: http://localhost:8100
      CONCOURSE_ADD_LOCAL_USER: dev:dev
      CONCOURSE_MAIN_TEAM_LOCAL_USER: dev
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
