version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: https://${DOMAIN}
        API_URL_BROWSER: https://${DOMAIN}
