version: '3.7'
services:
  proxy:
    image: traefik:v1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=DEBUG \
      --accessLog \
      --web
    labels:
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.enable=true
      - traefik.port=80
    ports:
      - '80:80'
  
  frontend:
    build:
      context: ./frontend
    labels:
      - traefik.frontend.rule=PathPrefix:/
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_TAG}

  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
    volumes:
      - /tmp/test-results:/tmp/test-results
      - ./backend/app:/app
    ports:
      - '5900'
    command: bash -c "while true; do sleep 1; done"
    env_file:
      - env-backend.env
    environment: &testenv
      - REVISION=${REVISION}
      - TAG=${TAG}
      - STACK_NAME=${STACK_NAME}
      - DEPLOYED_AT=${DEPLOYED_AT-}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_DB=${POSTGRES_DB:-corgi_dev}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD:-trust}
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      target: dev-runner
    env_file:
      - env-backend.env
    environment: *testenv
    labels:
      - traefik.frontend.rule=PathPrefix:/api,/docs,/redoc,/openapi.json
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_TAG}
# Uncomment lines below to create Infinite loop to keep container live doing nothing
#   backend:
#     command: bash -c "while true; do sleep 1; done"
    command: ./bin/prestart-dev.sh
    networks:
      default:
        aliases:
          - ${DOMAIN}
  db:
    image: postgres:12
    environment: *testenv
    

