version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        env: dev
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: http://backend
        API_URL_BROWSER: http://localhost
