services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      target: prod-runner
    environment:
      BACKEND_CORS_ORIGINS: http://localhost, http://localhost:3000
      DEPLOYED_AT: ''
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: dev
      SERVER_HOST: https://backend
      SERVER_NAME: backend
      STACK_NAME: dev
      TAG: dev
  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
    command: bash -c "while true; do sleep 1; done"
    environment:
      BACKEND_CORS_ORIGINS: http://localhost, http://localhost:3000
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: dev
      SERVER_NAME: backend
      STACK_NAME: dev
      TAG: dev
    ports:
    - target: 5900
    volumes:
    - /tmp/test-results:/tmp/test-results:rw
  db:
    environment:
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: dev
      SERVER_NAME: backend
      STACK_NAME: dev
      TAG: dev
    image: postgres:12
  frontend:
    build:
      context: ./frontend
version: '3.7'

