services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      target: prod-runner
    environment:
      BACKEND_CORS_ORIGINS: http://localhost, http://localhost:3000
      DEPLOYED_AT: ''
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: ${REVISION}
      STACK_NAME: ${STACK_NAME}
      TAG: ${TAG}
  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
    command: bash -c "while true; do sleep 1; done"
    environment:
      BACKEND_CORS_ORIGINS: http://localhost, http://localhost:3000
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: ${REVISION}
      PYTEST_BASE_URL: ${PYTEST_BASE_URL}
      STACK_NAME: ${STACK_NAME}
      TAG: ${TAG}
    ports:
    - target: 5900
    volumes:
    - ./backend/app:/app
    - /tmp/test-results:/tmp/test-results:rw
  db:
    environment:
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: ${REVISION}
      STACK_NAME: ${STACK_NAME}
      TAG: ${TAG}
    image: postgres:12
  frontend:
    build:
      context: ./frontend
version: '3.7'

