version: '3.7'
services:
  backend:
    image: 'openstax/output-producer-${DOCKER_IMAGE_BACKEND}:${TAG-latest}'
  frontend:
    image: 'openstax/output-producer-${DOCKER_IMAGE_FRONTEND}:${TAG-latest}'
