version: '3.7'
services:
  proxy:
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK}
      - default
  backend:
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK}
      - default
  frontend:
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK}
      - default

networks:
  traefik-public:
    external: true
