version: '3.7'
services:
  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
      args:
        env: dev
    volumes:
      - /tmp/test-results:/tmp/test-results
      - ./backend/app:/app
    ports:
      - '5900'
    command: bash -c "while true; do sleep 1; done"
    env_file:
      - env-backend.env
    environment: &testenv
      - SERVER_NAME=backend
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=tests
  backend:
    environment: *testenv
  frontend:
    build:
      args:
        API_URL: http://${DOMAIN}
        API_URL_BROWSER: http://${DOMAIN}
