networks:
  traefik-public:
    external: true
    name: traefik-public
services:
  backend:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: PathPrefix:/api,/docs,/redoc,/openapi.json
        traefik.port: '80'
        traefik.tags: traefik-staging
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 1
    environment:
      BACKEND_CORS_ORIGINS: http://localhost, http://localhost:3000
      DEPLOYED_AT: ${TAG}
      POSTGRES_DB: corgi-${PR_NUMBER}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: ${REVISION}
      SERVER_NAME: corgi-${PR_NUMBER}.ce.openstax.org
      STACK_NAME: ${STACK_NAME}
      TAG: ${TAG}
    image: openstax/corgi-backend:${TAG}
    logging:
      options:
        max-file: '5'
        max-size: 200m
    networks:
      default: {}
      traefik-public: {}
  db:
    deploy:
      placement:
        constraints:
        - node.labels.app-db-data == true
        - node.role == manager
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: corgi-${PR_NUMBER}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
    image: postgres:12
    logging:
      options:
        max-file: '5'
        max-size: 200m
    volumes:
    - app-db-data:/var/lib/postgresql/data/pgdata:rw
  frontend:
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: PathPrefix:/
        traefik.port: '80'
        traefik.tags: traefik-staging
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 1
    image: openstax/corgi-frontend:${TAG}
    logging:
      options:
        max-file: '5'
        max-size: 200m
    networks:
      default: {}
      traefik-public: {}
  proxy:
    command: --docker \ --docker.swarmmode \ --docker.watch \ --docker.exposedbydefault=false
      \ --constraints=tag==traefik-staging \ --logLevel=INFO \ --accessLog \ --web
    deploy:
      labels:
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.frontend.rule: Host:corgi-${PR_NUMBER}.ce.openstax.org
        traefik.port: '80'
        traefik.servicehttp.frontend.entryPoints: http
        traefik.tags: traefik-public
      placement:
        constraints:
        - node.labels.proxy == true
        - node.role == manager
    image: traefik:v1.7
    logging:
      options:
        max-file: '5'
        max-size: 200m
    networks:
      default: {}
      traefik-public: {}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.7'
volumes:
  app-db-data: {}

