services:
  backend:
    build:
      context: /Users/jma12/Projects/00_ce/corgi/backend
      dockerfile: backend.dockerfile
      target: prod-runner
    environment:
      BACKEND_CORS_ORIGINS: http://localhost, http://localhost:3000
      DEPLOYED_AT: '20210101.111111'
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: dev
      SERVER_HOST: https://backend
      SERVER_NAME: backend
      STACK_NAME: dev
      TAG: dev
  backend-tests:
    build:
      context: /Users/jma12/Projects/00_ce/corgi/backend
      dockerfile: tests.dockerfile
    command: bash -c "while true; do sleep 1; done"
    environment:
      BACKEND_CORS_ORIGINS: http://localhost, http://localhost:3000
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: dev
      SERVER_NAME: backend
      STACK_NAME: dev
      TAG: dev
    ports:
    - target: 5900
    volumes:
    - /Users/jma12/Projects/00_ce/corgi/backend/app:/app:rw
    - /tmp/test-results:/tmp/test-results:rw
  concourse:
    image: concourse/concourse:6.3
    privileged: true
  db:
    environment:
      POSTGRES_DB: tests
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ''
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REVISION: dev
      SERVER_NAME: backend
      STACK_NAME: dev
      TAG: dev
    image: postgres:12
  frontend:
    build:
      context: /Users/jma12/Projects/00_ce/corgi/frontend
  pgadmin:
    depends_on:
      db:
        condition: service_started
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cops.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: '5050'
    image: dpage/pgadmin4
version: '3.7'

