version: '3.7'
services:
  backend-tests:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        env: dev
    volumes:
      - ${TEST_RESULT_PATH:-./backend/app}:/test-results
    command: bash -c "while true; do sleep 1; done"
    env_file:
      - env-backend.env
    environment: &testenv
      - SERVER_NAME=backend
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=tests
  backend:
    environment: *testenv
