version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        env: dev
  frontend:
    build:
      context: ./frontend
  docs:
    build:
      context: ./docs
