version: "3.7"
services:
  proxy:
    logging:
      options:
        awslogs-stream: "${STACK_NAME}_proxy"
  frontend:
    logging:
      options:
        awslogs-stream: "${STACK_NAME}_frontend"
  backend:
    logging:
      options:
        awslogs-stream: "${STACK_NAME}_backend"
