---
resource_types:
  - name: output-producer
    type: docker-image
    source:
      repository: openstax/output-producer-resource

resources:
  - name: pdf-spike
    type: git
    source:
      uri: https://github.com/openstax/pdf-spike.git

  - name: cnx-recipes
    type: git
    source:
      uri: https://github.com/openstax/cnx-recipes.git

  - name: output-producer-queued
    type: output-producer
    source:
      api_root: ((pdf-job-queue-url))
      status_id: 1 # Queued

  - name: output-producer-updater
    type: output-producer
    source:
      api_root: ((pdf-job-queue-url))
      status_id: 0 # Placeholder

  - name: ce-pdf-spike
    type: s3
    source:
      bucket: ce-pdf-spike
      access_key_id: ((aws-sandbox-secret-key-id))
      secret_access_key: ((aws-sandbox-secret-access-key))
      skip_download: true

jobs:
  - name: bakery
    plan:
      - get: output-producer-queued
        trigger: true
        version: every

      - put: output-producer-updater
        params:
          id: output-producer-queued/id
          status_id: "2" # Assigned

      - get: pdf-spike
      - get: cnx-recipes

      - task: look up book
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: openstax/nebuchadnezzar

          inputs:
            - name: output-producer-queued
          outputs:
            - name: book

          run:
            path: /bin/bash
            args:
              - -cxe
              - |
                exec 2> >(tee book/stderr >&2)
                tail output-producer-queued/*
                cp output-producer-queued/id book/job_id
                cp output-producer-queued/collection_id book/collection_id
                cp output-producer-queued/version book/version
                cp output-producer-queued/content_server book/server
                wget -q -O jq 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64' && chmod +x jq
                server_name="$(cat output-producer-queued/job.json | ./jq -r '.content_server.name')"
                wget -q https://raw.githubusercontent.com/openstax/cnx-recipes/master/books.txt
                set +x
                . books.txt
                set -x
                for book_config in "${BOOK_CONFIGS[@]}"
                do
                  read -r book_name recipe_name _ book_colid _ <<< "$book_config"
                  if [ "$book_colid" == "$(cat book/collection_id)" ]
                  then
                    echo -n "$book_name" >book/name
                    echo -n "$recipe_name" >book/recipe
                  fi
                done
                echo -n "$(cat book/collection_id)-$(cat book/version)-${server_name}-$(cat book/job_id).pdf" >book/pdf_filename
                echo -n "https://ce-pdf-spike.s3.amazonaws.com/$(cat book/pdf_filename)" >book/pdf_url
                if [ ! -f book/name ]
                then
                  set +x
                  echo "Book not found" >book/stderr
                  exit 1
                fi
        on_success:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "3" # Processing
        on_failure:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "4" # Failed

      - task: fetch book
        file: pdf-spike/bakery/tasks/fetch-book.yml
        on_failure:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "4" # Failed

      - task: assemble-book
        file: pdf-spike/bakery/tasks/assemble-book.yml
        on_failure:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "4" # Failed

      - task: bake-book
        file: pdf-spike/bakery/tasks/bake-book.yml
        on_failure:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "4" # Failed

      - task: mathify-book
        file: pdf-spike/bakery/tasks/mathify-book.yml
        on_failure:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "4" # Failed

      - task: build-pdf
        file: pdf-spike/bakery/tasks/build-pdf.yml
        on_failure:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "4" # Failed

      - put: ce-pdf-spike
        params:
          file: artifacts/*.pdf
          acl: public-read
          content_type: application/pdf
        on_success:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "5" # Completed
            pdf_url: book/pdf_url
        on_failure:
          put: output-producer-updater
          params:
            id: output-producer-queued/id
            status_id: "4" # Failed
