---
resource_types:
  - name: s3-simple
    type: docker-image
    source:
      repository: 18fgsa/s3-resource-simple

  - name: output-producer
    type: docker-image
    source:
      repository: openstax/output-producer-resource

resources:
  - name: s3
    type: s3-simple
    source:
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      bucket: ((s3bucket))
      region: ((s3region))
      options:
        - "--exclude '*'"
        - "--include 'book/*'"

  - name: s3-artifacts
    type: s3
    source:
      bucket: ((s3bucket))
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      skip_download: true
      regexp: artifacts/(.*).pdf

  - name: cnx-recipes
    type: git
    source:
      uri: https://github.com/openstax/cnx-recipes.git

  - name: job-instructions
    type: git
    source:
      uri: https://github.com/openstax/pdf-spike.git

  - name: output-producer-queued
    type: output-producer
    source:
      api_root: ((pdf-job-queue-url))
      status_id: 1

  - name: event-status-updater
    type: output-producer
    source:
      api_root: ((pdf-job-queue-url))
      status_id: 0

jobs:
  - name: claim-work
    plan:
      - get: output-producer-queued
        trigger: true
        version: every
      - put: event-status-updater
        params:
          id: output-producer-queued/id
          status_id: "2" #Assigned

    on_success:
      put: event-status-updater
      params:
        id: output-producer-queued/id
        status_id: "3" #Processing

  - name: fetch-book
    plan:
      - get: output-producer-queued
        trigger: true
        passed: [claim-work]
      - get: job-instructions
      - task: look-up-book
        file: job-instructions/bakery/tasks/t-book-lookup.yml
      - task: fetch-book-via-neb
        file: job-instructions/bakery/tasks/t-fetch-book.yml

    on_failure:
      put: event-status-updater
      params:
        id: output-producer-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3

  - name: assemble-book
    plan:
      - get: output-producer-queued
        trigger: true
        passed: [fetch-book]
      - get: job-instructions
      - task: look-up-book
        file: job-instructions/bakery/tasks/t-book-lookup.yml
      - get: s3
    #- get: cnx-recipes
      - task: assemble-book-via-neb
        file: job-instructions/bakery/tasks/t-assemble-book.yml

    on_failure:
      put: event-status-updater
      params:
        id: output-producer-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3
      params:
        path: book

  - name: bake-book
    plan:
      - get: output-producer-queued
        trigger: true
        passed: [assemble-book]
      - get: job-instructions
      - task: look-up-book
        file: job-instructions/bakery/tasks/t-book-lookup.yml
      - get: s3
      - get: cnx-recipes
      - task: bake-book-via-easy-bake
        file: job-instructions/bakery/tasks/t-bake-book.yml

    on_failure:
      put: event-status-updater
      params:
        id: output-producer-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3
      params:
        path: book

  - name: mathify-book
    plan:
      - get: output-producer-queued
        trigger: true
        passed: [bake-book]
      - get: job-instructions
      - task: look-up-book
        file: job-instructions/bakery/tasks/t-book-lookup.yml
      - get: s3
      - task: mathify-book-via-mathify
        file: job-instructions/bakery/tasks/t-mathify-book.yml

    on_failure:
      put: event-status-updater
      params:
        id: output-producer-queued/id
        status_id: "4" #Failed
    on_success:
      put: s3
      params:
        path: book

  - name: generate-pdf
    plan:
      - get: output-producer-queued
        trigger: true
        passed: [mathify-book]
      - get: job-instructions
      - task: look-up-book
        file: job-instructions/bakery/tasks/t-book-lookup.yml
      - get: s3
      - task: pdf-book-via-princexml
        file: job-instructions/bakery/tasks/t-build-pdf.yml
      - put: s3-artifacts
        params:
          file: artifacts/*.pdf
          acl: public-read
          content_type: application/pdf

    on_failure:
      put: event-status-updater
      params:
        id: output-producer-queued/id
        status_id: "4" #Failed
    on_success:
      put: event-status-updater
      params:
        id: output-producer-queued/id
        status_id: "5"
        pdf_url: artifacts/pdf_url
