---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/nebuchadnezzar

inputs:
  - name: book
  - name: fetched-book
outputs:
  - name: assembled-book

run:
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee assembled-book/stderr >&2)
      rm -f fetched-book/stderr
      cp -r fetched-book/* assembled-book
      cd assembled-book
      book_dir="../assembled-book/$(cat ../book/name)"
      neb assemble "$book_dir/raw" "$book_dir"
