---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/nebuchadnezzar

inputs:
  - name: book
outputs:
  - name: fetched-book

run:
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee fetched-book/stderr >&2)
      cd fetched-book
      book_dir="$(cat ../book/name)"
      mkdir -p "$book_dir" ~/.config/
      server="$(cat ../book/server)"
      cat >~/.config/nebuchadnezzar.ini <<EOF
      [settings]
      [environ-$server]
      url = https://$server
      EOF
      yes | neb get -r -d "$book_dir/raw" "$(cat ../book/server)" "$(cat ../book/collection_id)" "$(cat ../book/version)"
