---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/nebuchadnezzar
    tag: latest
inputs:
  - name: workflow-events-queued
outputs:
  - name: book-title
run:
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee book-title/stderr >&2)
      tail workflow-events-queued/*
      cp workflow-events-queued/id              book-title/id
      cp workflow-events-queued/collection_id   book-title/collection_id
      cp workflow-events-queued/version         book-title/version
      cp workflow-events-queued/content_server  book-title/server
      wget -q https://raw.githubusercontent.com/openstax/cnx-recipes/master/books.txt
      set +x
      . books.txt
      set -x
      for book_config in "${BOOK_CONFIGS[@]}"
      do
        read -r book_name recipe_name _ book_colid _ <<< "$book_config"
        if [ "$book_colid" == "$(cat book-title/collection_id)" ]
        then
          echo -n "$recipe_name" >book-title/recipe
          echo -n "$book_name" >book-title/name
        fi
      done
      echo -n latest >book-title/version
      if [ ! -f book-title/collection_id ]
      then
        set +x
        echo "Book not found" >book-title/stderr
        exit 1
      fi
