---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/nebuchadnezzar
    tag: latest

inputs:
  - name: book-title
outputs:
  - name: book

run:
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee book/stderr >&2)
      yes | neb get -r -d "./temp" "$(cat book-title/server | cut -f1 -d".")" "$(cat book-title/collection_id)" "$(cat book-title/version)"
      mv temp/* book
