---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openstax/nebuchadnezzar
    tag: latest

inputs:
  - name: book-title
outputs:
  - name: book

run:
  path: /bin/bash
  args:
    - -cxe
    - |
      exec 2> >(tee book/stderr >&2)
      mkdir -p ~/.config/
      server="$(cat book-title/server)"
      cat >~/.config/nebuchadnezzar.ini <<EOF
      [settings]
      [environ-$server]
      url = https://$server
      EOF
      yes | neb get -r -d "./temp" "$(cat book-title/server)" "$(cat book-title/collection_id)" "$(cat book-title/version)"
      mv temp/* book
