version: 2.0
jobs:
  integration-test:
    machine:
      image: ubuntu-1604:201903-01

    environment:
      TEST_RESULTS_DIR: /tmp/test-results
      TEST_RESULTS: /tmp/test-results/junit.xml

    steps:
      - checkout
      # Permissions errors occurred with 0775 due to
      # docker user not having permissions over this folder.
      - run: mkdir -p -m=0777 $TEST_RESULTS_DIR

      - run:
          name: Run integration and ui tests
          command: |
            ./scripts/tests.ci.sh

      - store_artifacts:
          path: /tmp/test-results/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-results

  cli-functional-test:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Install node
          command: |
            export NVM_DIR=/opt/circleci/.nvm
            [ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"
            nvm install v12.16.1
            nvm alias default v12.16.1
            echo 'export NVM_DIR=/opt/circleci/.nvm' >> $BASH_ENV
            echo "[ -s \"${NVM_DIR}/nvm.sh\" ] && . \"${NVM_DIR}/nvm.sh\"" >> $BASH_ENV

      - run:
          name: Setup fly
          command: |
            mkdir -p ~/.local/bin
            curl -L https://github.com/concourse/concourse/releases/download/v6.0.0/fly-6.0.0-linux-amd64.tgz -o fly.tgz
            tar -xvzf fly.tgz
            chmod +x fly
            mv fly ~/.local/bin
            echo 'export PATH=${HOME}/.local/bin:${PATH}' >> $BASH_ENV

      - run:
          name: Run tests
          command: |
            node --version
            fly --version
            cd ./bakery
            npm install
            npm run test

  bakery-scripts-test:
    docker:
      - image: openstax/cops-bakery-scripts

    steps:
      - checkout

      - run:
          name: Setup test environment
          command: |
            mkdir -p /tmp/test-reports
            pip install pytest

      - run:
          name: Run bakery scripts tests
          command: |
            pytest bakery -vvv --junitxml=/tmp/test-reports/junit.xml

      - store_artifacts:
          path: /tmp/test-reports/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-reports

  lint-bakery:
    docker:
      - image: circleci/node:12-buster

    steps:
      - checkout
      - run:
          name: install
          command: |
            cd ./bakery
            npm install
            npm run lint

workflows:
  version: 2
  run-tests:
    jobs:
      - integration-test
      - cli-functional-test
      - bakery-scripts-test
      - lint-bakery
