version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
  python: circleci/python@2.0.3
jobs:

  frontend-unit:
    docker:
      - image: node:16-alpine

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd ./frontend
            npm ci
            npm run test:unit
  
  backend-unit:
    executor: python/default

    environment:
      SESSION_SECRET: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          app-dir: ./backend/app
      - run:
          name: Run unit tests
          command: |

            cd ./backend/app
            poetry install
            poetry run pytest -vvv --junitxml=/tmp/test-reports/junit.xml ./tests/unit
      
      - store_artifacts:
          path: /tmp/test-reports/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  run-tests:
    jobs:
      - frontend-unit
      - backend-unit
      - shellcheck/check:
          path: ./
