version: 2.0
jobs:
  integration-test:
    machine:
      image: ubuntu-1604:201903-01

    environment:
      TEST_RESULTS_DIR: /tmp/test-results
      TEST_RESULTS: /tmp/test-results/junit.xml

    steps:
      - checkout
      # Permissions errors occurred with 0775 due to 
      # docker user not having permissions over this folder.
      - run: mkdir -p -m=0777 $TEST_RESULTS_DIR

      - run:
          name: Run integration and ui tests
          command: |
            ./scripts/tests.ci.sh

      - store_artifacts:
          path: /tmp/test-results/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-results

  bakery-test:
    docker:
      - image: openstax/cops-bakery-scripts

    steps:
      - checkout

      - run:
          name: Setup test environment
          command: |
            mkdir -p /tmp/test-reports
            pip install pytest

      - run:
          name: Run bakery scripts tests
          command: |
            pytest bakery -vvv --junitxml=/tmp/test-reports/junit.xml

      - store_artifacts:
          path: /tmp/test-reports/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  run-tests:
    jobs:
      - integration-test
      - bakery-test
