version: 2.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    
    environment:
      TEST_RESULTS: /tmp/test-results
      
    steps:
      - checkout
    
      - run: mkdir -p $TEST_RESULTS
      
      - run: 
          name: Run integration tests
          command: |
            ./scripts/tests.sh
