version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    
    environment:
      TEST_RESULTS: /tmp/test-results
      
    steps:
      - checkout
    
      - run: mkdir -p $TEST_RESULTS
      
      - setup_remote_docker
      
      - run: 
          name: Run integration tests
          command: |
            ./scripts/tests.sh
