version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  integration-test:
    machine:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true

    environment:
      TEST_RESULTS_DIR: /tmp/test-results
      TEST_RESULTS: /tmp/test-results/junit.xml

    steps:
      - checkout
      # Permissions errors occurred with 0775 due to
      # docker user not having permissions over this folder.
      - run: mkdir -p -m=0777 $TEST_RESULTS_DIR

      - run:
          name: Run integration and ui tests
          command: |
            ./scripts/tests.ci.sh

      - store_artifacts:
          path: /tmp/test-results/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-results

  bakery-scripts-test:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run:
          name: Setup test environment
          command: |
            sudo apt-get update
            sudo apt-get install -y imagemagick icc-profiles-free ghostscript
            mkdir -p /tmp/test-reports
            pip install bakery/src/scripts/.[test]

      - run:
          name: Lint bakery Python scripts
          command: |
            flake8 bakery/src/**/**.py --max-line-length=100

      - run:
          name: Run bakery scripts tests
          command: |
            pytest --cov=bakery_scripts --cov-report=html --cov-report=term bakery -vvv --junitxml=/tmp/test-reports/junit.xml

      - run:
          name: Upload code coverage results
          command: |
            bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: /tmp/test-reports/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-reports

  frontend-unit:
    docker:
      - image: circleci/node:12-buster

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd ./frontend
            npm ci
            npm run test:unit

  lint-bakery:
    docker:
      - image: circleci/node:12-buster

    steps:
      - checkout
      - run:
          name: Install and lint
          command: |
            cd ./bakery
            npm install
            npm run lint

workflows:
  version: 2
  run-tests:
    jobs:
      - integration-test
      - bakery-scripts-test
      - lint-bakery
      - frontend-unit
      - shellcheck/check:
          path: ./
