version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  integration-test:
    machine:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true

    environment:
      TEST_RESULTS_DIR: /tmp/test-results
      TEST_RESULTS: /tmp/test-results/junit.xml

    steps:
      - checkout
      # Permissions errors occurred with 0775 due to
      # docker user not having permissions over this folder.
      - run: mkdir -p -m=0777 $TEST_RESULTS_DIR

      - run:
          name: Run integration and ui tests
          command: |
            ./scripts/tests.ci.sh

      - store_artifacts:
          path: /tmp/test-results/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-results

  frontend-unit:
    docker:
      - image: circleci/node:12-buster

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd ./frontend
            npm ci
            npm run test:unit

workflows:
  version: 2
  run-tests:
    jobs:
      - integration-test
      - frontend-unit
      - shellcheck/check:
          path: ./
