version: 2.1
orbs:
  shellcheck: circleci/shellcheck@3.1.2
  python: circleci/python@2.0.3
jobs:
  frontend-unit:
    docker:
      - image: node:16-alpine

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd ./frontend
            npm ci
            npm run build
            npm run test:unit
  
  backend-unit:
    executor: python/default

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          app-dir: ./backend/app
      - run:
          name: Run unit tests
          command: |
            cd ./backend/app
            poetry install --no-root --no-interaction --no-ansi
            poetry run pytest -vvv --junitxml=/tmp/test-reports/junit.xml ./tests/unit

      - store_artifacts:
          path: /tmp/test-reports/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-reports

  build-backend:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build backend image
          command: |
            diff="$(git diff --name-only ${CIRCLE_SHA1} || git diff --name-only main)"
            if echo "$diff" | grep "backend/" > /dev/null; then
              cd ./backend
              docker build -f backend.dockerfile --target prod-runner .
            fi

workflows:
  version: 2
  run-tests:
    jobs:
      - shellcheck/check:
          dir: ./scripts
          pattern: "*.sh"
          exclude: SC1091
      - shellcheck/check:
          dir: ./backend/app/bin
          pattern: "*.sh"
          exclude: SC1091
      - shellcheck/check:
          dir: "."
          pattern: corgi
      - frontend-unit
      - backend-unit
      - build-backend
