"""Add approved book table and child tables

Revision ID: 3e801ba4d7e0
Revises: fd185b46ac05
Create Date: 2024-02-26 20:13:21.678327

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e801ba4d7e0'
down_revision = 'fd185b46ac05'
branch_labels = None
depends_on = None


utcnow = datetime.utcnow()
consumer_table = sa.table('consumer',
                    sa.column('id', sa.Integer),
                    sa.column('name', sa.String),
                    sa.column('created_at', sa.DateTime),
                    sa.column('updated_at', sa.DateTime)
                    )


def insert_consumers():
    to_insert = [
        {"id": 1, "name": "REX", "created_at": utcnow, "updated_at": utcnow}
    ]
    bind = op.get_bind()
    insert = consumer_table.insert().values(to_insert)
    bind.execute(insert)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_version_created_at'), 'code_version', ['created_at'], unique=False)
    op.create_index(op.f('ix_code_version_id'), 'code_version', ['id'], unique=False)
    op.create_index(op.f('ix_code_version_updated_at'), 'code_version', ['updated_at'], unique=False)
    op.create_table('consumer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_created_at'), 'consumer', ['created_at'], unique=False)
    op.create_index(op.f('ix_consumer_id'), 'consumer', ['id'], unique=False)
    op.create_index(op.f('ix_consumer_updated_at'), 'consumer', ['updated_at'], unique=False)
    op.create_table('approved_book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=False),
    sa.Column('code_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['code_version_id'], ['code_version.id'], ),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'consumer_id', 'code_version_id')
    )
    op.create_index(op.f('ix_approved_book_book_id'), 'approved_book', ['book_id'], unique=False)
    op.create_index(op.f('ix_approved_book_code_version_id'), 'approved_book', ['code_version_id'], unique=False)
    op.create_index(op.f('ix_approved_book_consumer_id'), 'approved_book', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_approved_book_created_at'), 'approved_book', ['created_at'], unique=False)
    op.create_index(op.f('ix_approved_book_updated_at'), 'approved_book', ['updated_at'], unique=False)
    op.drop_column('book_job', 'approved')
    # ### end Alembic commands ###
    insert_consumers()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_job', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_approved_book_updated_at'), table_name='approved_book')
    op.drop_index(op.f('ix_approved_book_created_at'), table_name='approved_book')
    op.drop_index(op.f('ix_approved_book_consumer_id'), table_name='approved_book')
    op.drop_index(op.f('ix_approved_book_code_version_id'), table_name='approved_book')
    op.drop_index(op.f('ix_approved_book_book_id'), table_name='approved_book')
    op.drop_table('approved_book')
    op.drop_index(op.f('ix_consumer_updated_at'), table_name='consumer')
    op.drop_index(op.f('ix_consumer_id'), table_name='consumer')
    op.drop_index(op.f('ix_consumer_created_at'), table_name='consumer')
    op.drop_table('consumer')
    op.drop_index(op.f('ix_code_version_updated_at'), table_name='code_version')
    op.drop_index(op.f('ix_code_version_id'), table_name='code_version')
    op.drop_index(op.f('ix_code_version_created_at'), table_name='code_version')
    op.drop_table('code_version')
    # ### end Alembic commands ###
