"""add PipelineVersion table

Revision ID: 6fc2c2cef8a9
Revises: a853887ac719
Create Date: 2026-02-25 22:47:01.890523

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6fc2c2cef8a9"
down_revision = "a853887ac719"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_version",
        sa.Column("code_version_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_version_id"],
            ["code_version.id"],
        ),
        sa.PrimaryKeyConstraint("code_version_id"),
        sa.UniqueConstraint("position", name="_unique_pipeline_position"),
    )
    op.create_index(
        op.f("ix_pipeline_version_code_version_id"),
        "pipeline_version",
        ["code_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_version_position"),
        "pipeline_version",
        ["position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pipeline_version_position"), table_name="pipeline_version"
    )
    op.drop_index(
        op.f("ix_pipeline_version_code_version_id"),
        table_name="pipeline_version",
    )
    op.drop_table("pipeline_version")
    # ### end Alembic commands ###
