"""renamed content-distribution to web-hosting

Revision ID: a6c1c315d2d3
Revises: 7744a6c02085
Create Date: 2021-01-22 20:15:41.945552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c1c315d2d3'
down_revision = '7744a6c02085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_types_created_at'), 'job_types', ['created_at'], unique=False)
    op.drop_index('ix_jobs_job_type', table_name='jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_job_type', 'jobs', ['job_type_id'], unique=False)
    op.drop_index(op.f('ix_job_types_created_at'), table_name='job_types')
    # ### end Alembic commands ###
