"""fix UserRepository primary key

Revision ID: fd185b46ac05
Revises: 603c41a55f80
Create Date: 2023-12-04 20:50:24.612968

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "fd185b46ac05"
down_revision = "603c41a55f80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_repository_pkey", "user_repository", type_="primary"
    )
    op.create_primary_key(
        "user_repository_pkey", "user_repository", ["user_id", "repository_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_repository_pkey", "user_repository", type_="primary"
    )
    op.create_primary_key(
        "user_repository_pkey",
        "user_repository",
        ["user_id", "repository_id", "permission_id"],
    )
    # ### end Alembic commands ###
