line-length = 80

exclude = [
    ".tox",
    ".git",
    ".venv",
    ".env",
    "build*.py"
]

[lint.mccabe]
max-complexity = 18

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # McCabe complexity
    "C",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    "W"
]
ignore = ["F401", "B008", "B006", "UP022"]
fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true