line-length = 80

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["F401", "B008", "B006", "UP022"]
fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true