[tool.poetry]
name = "app"
version = "0.0.0"
description = ""
authors = []
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "0.75.2"
gunicorn = "20.1.0"
psycopg2-binary = "^2.9.2"
tenacity = "6.0.0"
uvicorn = "0.15.0"
SQLAlchemy = "1.4.36"
alembic = "1.7.7"
lxml = "4.9.0"
requests = "2.27.1"
httpx = "^0.23.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-testrail = "^2.9.0"
importlib-metadata = "^4.8.2"
playwright = "1.22"
pytest-base-url = "^2.0.0"
pytest-mock = "^3.7.0"
python-dotenv = "^0.21.0"
