[tool.poetry]
name = "app"
version = "0.0.0"
description = ""
authors = []
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "0.75.2"
gunicorn = "20.1.0"
psycopg2-binary = "^2.9.2"
tenacity = "6.0.0"
uvicorn = "0.15.0"
SQLAlchemy = "1.4.36"
alembic = "1.7.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-testrail = "^2.9.0"
importlib-metadata = "^4.8.2"
playwright = "^1.19.0"
pytest-base-url = "^2.0.0"
pytest-mock = "^3.7.0"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
