[tool.poetry]
name = "backend"
version = "0.0.0"
description = ""
authors = []
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
alembic = "^1.4.2"
Click = "^7.1.2"
fastapi = "^0.56.0"
gunicorn = "^20.0.4"
h11 = "^0.9.0"
httptools = "^0.1.1"
jinja2 = "^2.11.2"
mako = "^1.1.3"
markupsafe = "^1.1.1"
psycopg2-binary = "^2.8.5"
pydantic = "^1.5.1"
starlette = "0.13.2"

[tool.poetry.dev-dependencies]
appnope = "^0.1.0"
attrs = "^19.3.0"
backcall = "^0.2.0"
bleach = "^3.1.5"
certifi = "^2020.4.5"
chardet = "^3.0.4"
chromedriver-binary = "83.0.4103.39.0"
defusedxml = "^0.6.0"
entrypoints = "^0.3"
idna = "^2.9"
importlib-metadata = "^1.6.1"
ipykernel = "^5.3.0"
ipython = "^7.15.0"
ipython-genutils = "^0.2.0"
jedi = "^0.17.0"
json5 = "^0.9.5"
jsonschema = "^3.2.0"
jupyter-client = "^6.1.3"
jupyter-core = "^4.6.3"
jupyterlab = "^2.1.4"
jupyterlab-server = "^1.1.5"
markupsafe = "^1.1.1"
mistune = "^0.8.4"
more-itertools = "^8.3.0"
nbconvert = "^5.6.1"
nbformat = "^5.0.7"
notebook = "^6.0.3"
packaging = "^20.4"
pandocfilters = "^1.4.2"
parso = "^0.7.0"
pexpect = "^4.8.0"
pickleshare = "^0.7.5"
pluggy = "^0.13.1"
prometheus-client = "^0.8.0"
prompt-toolkit = "^3.0.5"
ptyprocess = "^0.6.0"
py = "^1.8.1"
pygments = "^2.6.1"
pyparsing = "^2.4.7"
pypom = "^2.2.0"
pyrsistent = "^0.16.0"
pytest = "^5.4.3"
pytest-selenium = "^1.17.0"
python-dateutil = "^2.8.1"
pyzmq = "^19.0.1"
requests = "^2.23.0"
Send2Trash = "^1.5.0"
six = "^1.15.0"
terminado = "^0.8.3"
testpath = "^0.4.4"
tornado = "^6.0.4"
traitlets = "^4.3.3"
urllib3 = "^1.25.9"
wcwidth = "^0.2.4"
webencodings = "^0.5.1"
zipp = "^3.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
